<div id="left-pane">
    <?= $this->sidebarButtons ?>

    <div id="searchFormWrapper">
        <form id="searchForm" class="searchForm"
              action="<?= $this->baseUrl ?>/<?= $this->moduleName ?>/<?= $this->controllerName ?>/search" method="post">
            <div class="hidden"><?= $this->formHidden('viewParam', $this->viewParam, array()) ?></div>

            <div>
                <label><?= $this->getTranslation('projectnumber_search'); ?>:</label>
                <?= $this->formText('projectnumber_search', '', array('size' => 30, 'class' => 'text')); ?>
            </div>
            <div>
                <label><?= $this->getTranslation('name_search'); ?>:</label>
                <?= $this->formText('filter_name', '', array('size' => 30, 'class' => 'text')); ?>
            </div>
            <div>
                <label><?= $this->getTranslation('zipcode_search'); ?>:</label>
                <?= $this->formText('zipcode', '', array('size' => 30, 'class' => 'text')); ?>
            </div>
            <div>
                <label><?= $this->getTranslation('objecttype_search') ?>:</label>
                <?= $this->formSelect('objecttype_search', null, array('style' => 'width: 150px;', 'multiple' => 'multiple', 'size' => 5), $this->objecttypeOptions) ?>
            </div>
            <div>
                <?= $this->fieldSelect('projectnewTaskTypeId', null, 'projectnew_task_type_id', array('style' => 'width: 150px;'), $this->taskTypeOptions, $this->getTranslation('select_option')) ?>
            </div>
            <div>
                <label><?= $this->getTranslation('status_id') ?>:</label>
                <?= $this->formSelect('status_id', $this->statusOptionsSelected, array('style' => 'width: 150px;', 'multiple' => 'multiple', 'size' => 5), $this->statusOptions) ?>
            </div>
            <div>
                <label><?= $this->getTranslation('assigned_group_search') ?>:</label>
                <?= $this->formSelect('assigned_group', null, array('style' => 'width: 150px;', 'multiple' => 'multiple', 'size' => 5), $this->assignedGroupOptions) ?>
            </div>
            <div>
                <?= $this->formHidden('userIdSearch', $this->userId) ?>
                <label><?= $this->getTranslation('assigned_to_label'); ?>:</label>
                <?= $this->formText('acUserSearch', $this->userFullName, array('size' => 30)) ?>
            </div>
            <div style="float:left; clear:both; width:100%;">
                <?php echo $this->formCheckbox('notassigned_search', '1', array('style' => 'margin:2px;', 'onclick' => 'toggleAssignedTo()'), array()); ?>
                <span style="float:left; margin-top:2px;"><?php echo $this->getTranslation('notassigned_search'); ?></span>
            </div>
            <div>
                <label for="filter_startdate"><?=$this->getTranslation('startdate_label')?></label>
                <input type="text" id="filter_startdate" class="date-picker" name="filter_startdate" />
            </div>
            <div>
                <label for="filter_enddate"><?=$this->getTranslation('enddate_label')?></label>
                <input type="text" id="filter_enddate" class="date-picker" name="filter_enddate" />
            </div>

            <div style="clear:both;">
                <br />
                <?php echo $this->formSubmit('search', $this->getTranslation('search'), array('class' => 'button')) ?>
                <?php echo $this->formButton('reset', $this->getTranslation('reset'), array('class' => 'button', 'onclick' => 'resetSearchForm()')); ?>
            </div>

        </form>

    </div>

</div>

<div id="right-pane">
    <div id="list"></div>
    <div id="properties"></div>
</div>